name: Bicep Issue 15696
on:
  workflow_dispatch:
jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: bicep restore test.bicep
  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: bicep restore test.bicep
